import React, { useState } from 'react';
import { Bot, Sparkles, Check, AlertCircle, Save, RotateCcw } from 'lucide-react';
import { api } from '../../lib/api';
import type { Question } from '../../types';

interface AiQuizGeneratorProps {
    adminId: string;
    onQuizCreated: () => void;
    onNotification: (type: 'success' | 'error', message: string) => void;
}

const AiQuizGenerator: React.FC<AiQuizGeneratorProps> = ({ adminId, onQuizCreated, onNotification }) => {
    const [step, setStep] = useState<1 | 2>(1);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Form State
    const [material, setMaterial] = useState('');
    const [styleExamples, setStyleExamples] = useState('');
    const [questionCount, setQuestionCount] = useState(10);
    const [difficulty, setDifficulty] = useState('Medium');
    const [questionType, setQuestionType] = useState('Multiple Choice');
    const [file, setFile] = useState<File | null>(null);
    const [styleFile, setStyleFile] = useState<File | null>(null);

    // Generated Data
    const [generatedQuestions, setGeneratedQuestions] = useState<Question[]>([]);
    const [quizTitle, setQuizTitle] = useState('AI Generated Quiz');
    const [quizDescription, setQuizDescription] = useState('Generated by AI Assistant based on study material.');

    const handleGenerate = async () => {
        if (!material.trim() && !file) {
            setError('Please provide study material (text or file).');
            return;
        }

        setLoading(true);
        setError(null);
        try {
            const formData = new FormData();
            formData.append('material', material);
            formData.append('styleExamples', styleExamples);
            formData.append('questionCount', questionCount.toString());
            formData.append('difficulty', difficulty);
            formData.append('questionType', questionType);
            if (file) {
                formData.append('file', file);
            }
            if (styleFile) {
                formData.append('styleFile', styleFile);
            }

            const response = await api.generateAiQuiz(formData, adminId);

            if (response.success && response.data) {
                setGeneratedQuestions(response.data);
                setStep(2);
                onNotification('success', 'Quiz generated successfully! Please review.');
            } else {
                setError('Failed to generate quiz. No data returned.');
            }
        } catch (err: any) {
            console.error(err);
            setError(err.message || 'Failed to communicate with AI service.');
        } finally {
            setLoading(false);
        }
    };

    const handlePublish = async () => {
        setLoading(true);
        try {
            const quizData = {
                id: `ai-quiz-${Date.now()}`, // Generate a unique ID
                title: quizTitle,
                description: quizDescription,
                category: 'AI Generated', // Default category
                difficulty,
                timeLimit: questionCount * 1.5, // Estimate 1.5 min per question
                passingScore: 70,
                questions: generatedQuestions,
                reviewMode: true
            };

            await api.createQuiz(quizData, adminId);
            onNotification('success', 'Quiz published successfully!');
            onQuizCreated();

            // Reset
            setStep(1);
            setMaterial('');
            setGeneratedQuestions([]);
        } catch (err: any) {
            setError(err.message || 'Failed to publish quiz.');
            onNotification('error', 'Failed to publish quiz.');
        } finally {
            setLoading(false);
        }
    };

    const handleQuestionChange = (index: number, field: keyof Question, value: any) => {
        const updated = [...generatedQuestions];
        updated[index] = { ...updated[index], [field]: value };
        setGeneratedQuestions(updated);
    };

    const handleOptionChange = (qIndex: number, oIndex: number, value: string) => {
        const updated = [...generatedQuestions];
        const newOptions = [...(updated[qIndex].options || [])];
        newOptions[oIndex] = value;
        updated[qIndex].options = newOptions;
        setGeneratedQuestions(updated);
    };

    if (loading) {
        return (
            <div className="flex flex-col items-center justify-center p-12 text-center h-full min-h-[400px]">
                <div className="relative mb-6">
                    <div className="absolute inset-0 bg-purple-500/20 rounded-full blur-xl animate-pulse"></div>
                    <Bot className="w-16 h-16 text-purple-600 animate-bounce relative z-10" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                    {step === 1 ? 'AI is analyzing your material...' : 'Publishing Quiz...'}
                </h3>
                <p className="text-gray-500 max-w-md">
                    {step === 1 ? 'This usually takes about 10-30 seconds depending on the length of the material.' : 'Saving to database...'}
                </p>
                <div className="mt-8 flex gap-2">
                    <div className="w-2 h-2 bg-purple-600 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                    <div className="w-2 h-2 bg-purple-600 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                    <div className="w-2 h-2 bg-purple-600 rounded-full animate-bounce"></div>
                </div>
            </div>
        );
    }

    return (
        <div className="h-full flex flex-col">
            {/* Header */}
            <div className="mb-6 flex items-center justify-between">
                <div>
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                        <Sparkles className="w-6 h-6 text-purple-500" />
                        AI Quiz Generator
                    </h2>
                    <p className="text-gray-500 dark:text-gray-400">
                        Create high-quality quizzes in seconds using artificial intelligence.
                    </p>
                </div>
                {step === 2 && (
                    <button
                        onClick={() => setStep(1)}
                        className="text-sm font-medium text-gray-500 hover:text-gray-900 dark:hover:text-white flex items-center gap-1"
                    >
                        <RotateCcw className="w-4 h-4" />
                        Start Over
                    </button>
                )}
            </div>

            {error && (
                <div className="mb-6 bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-500/20 text-red-600 dark:text-red-400 p-4 rounded-xl flex items-center gap-3">
                    <AlertCircle className="w-5 h-5 flex-shrink-0" />
                    <p>{error}</p>
                </div>
            )}

            {step === 1 ? (
                /* STEP 1: INPUT AND CONFIGURATION */
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 h-full overflow-hidden">
                    <div className="lg:col-span-2 flex flex-col gap-6 h-full overflow-y-auto pr-2 custom-scrollbar">
                        {/* Study Material */}
                        <div className="card p-6 rounded-2xl bg-white dark:bg-[#13141f] border border-gray-200 dark:border-white/5 shadow-sm">
                            <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-2">
                                Study Material (Text)
                            </label>
                            <p className="text-xs text-gray-500 mb-3">
                                Paste lecture notes, articles, or documentation here.
                            </p>
                            <textarea
                                value={material}
                                onChange={(e) => setMaterial(e.target.value)}
                                placeholder="# Introduction to Biology..."
                                className="w-full h-64 p-4 rounded-xl bg-gray-50 dark:bg-black/20 border border-gray-200 dark:border-white/10 focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none font-mono text-sm leading-relaxed mb-4"
                            />

                            <div className="relative border-2 border-dashed border-gray-200 dark:border-white/10 rounded-xl p-6 text-center hover:border-purple-500/50 transition-colors bg-gray-50/50 dark:bg-black/20">
                                <input
                                    type="file"
                                    accept=".pdf,.pptx,.txt,.md"
                                    onChange={(e) => setFile(e.target.files?.[0] || null)}
                                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                                />
                                <div className="space-y-2 pointer-events-none">
                                    <div className="mx-auto w-12 h-12 rounded-full bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center text-purple-600 dark:text-purple-400">
                                        <Sparkles className="w-6 h-6" />
                                    </div>
                                    <p className="text-sm font-bold text-gray-900 dark:text-white">
                                        {file ? file.name : 'Upload PDF or PPTX'}
                                    </p>
                                    <p className="text-xs text-gray-500">
                                        or drag and drop file here
                                    </p>
                                </div>
                                {file && (
                                    <button
                                        onClick={(e) => { e.preventDefault(); setFile(null); }}
                                        className="absolute top-2 right-2 p-1 bg-red-100 text-red-600 rounded-full hover:bg-red-200 z-10"
                                    >
                                        <div className="w-4 h-4 flex items-center justify-center font-bold">×</div>
                                    </button>
                                )}
                            </div>
                        </div>

                        {/* Formatting Instructions (Optional) */}
                        <div className="card p-6 rounded-2xl bg-white dark:bg-[#13141f] border border-gray-200 dark:border-white/5 shadow-sm">
                            <div className="flex items-center justify-between mb-2">
                                <label className="block text-sm font-bold text-gray-700 dark:text-gray-300">
                                    Style Guide & Instructions (Optional)
                                </label>
                                <span className="text-xs px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 font-bold">Advanced</span>
                            </div>
                            <p className="text-xs text-gray-500 mb-3">
                                Provide examples of "good" questions or "how the doctor thinks".
                            </p>
                            <textarea
                                value={styleExamples}
                                onChange={(e) => setStyleExamples(e.target.value)}
                                placeholder="Example: Focus on 'Mechanism of Action' rather than rote memorization. Format questions as clinical vignettes..."
                                className="w-full h-32 p-4 rounded-xl bg-gray-50 dark:bg-black/20 border border-gray-200 dark:border-white/10 focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none text-sm mb-4"
                            />

                            <div className="relative border-2 border-dashed border-gray-200 dark:border-white/10 rounded-xl p-4 text-center hover:border-blue-500/50 transition-colors bg-gray-50/50 dark:bg-black/20">
                                <input
                                    type="file"
                                    accept=".pdf,.pptx,.txt,.md"
                                    onChange={(e) => setStyleFile(e.target.files?.[0] || null)}
                                    className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                                />
                                <div className="space-y-1 pointer-events-none">
                                    <p className="text-xs font-bold text-gray-700 dark:text-gray-300">
                                        {styleFile ? styleFile.name : 'Upload Style Guide (PDF/PPTX)'}
                                    </p>
                                    {!styleFile && <p className="text-[10px] text-gray-500">Optional: Upload an old exam or style doc</p>}
                                </div>
                                {styleFile && (
                                    <button
                                        onClick={(e) => { e.preventDefault(); setStyleFile(null); }}
                                        className="absolute top-1 right-1 p-1 bg-red-100 text-red-600 rounded-full hover:bg-red-200 z-10"
                                    >
                                        <div className="w-3 h-3 flex items-center justify-center font-bold text-xs">×</div>
                                    </button>
                                )}
                            </div>
                        </div>
                    </div>

                    <div className="flex flex-col gap-6">
                        {/* Configuration Panel */}
                        <div className="card p-6 rounded-2xl bg-white dark:bg-[#13141f] border border-gray-200 dark:border-white/5 shadow-sm sticky top-0">
                            <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-6">Quiz Settings</h3>

                            <div className="space-y-6">
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Number of Questions</label>
                                    <div className="flex items-center gap-4">
                                        <input
                                            type="range"
                                            min="3"
                                            max="30"
                                            value={questionCount}
                                            onChange={(e) => setQuestionCount(parseInt(e.target.value))}
                                            className="flex-1 accent-purple-600"
                                        />
                                        <span className="font-bold text-2xl w-12 text-center text-gray-900 dark:text-white">{questionCount}</span>
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Difficulty</label>
                                    <div className="grid grid-cols-3 gap-2">
                                        {['Easy', 'Medium', 'Hard'].map((lvl) => (
                                            <button
                                                key={lvl}
                                                onClick={() => setDifficulty(lvl)}
                                                className={`py-2 px-3 rounded-xl text-sm font-bold transition-all ${difficulty === lvl
                                                    ? 'bg-purple-600 text-white shadow-lg shadow-purple-500/30'
                                                    : 'bg-gray-100 dark:bg-white/5 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-white/10'
                                                    }`}
                                            >
                                                {lvl}
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Question Type</label>
                                    <select
                                        value={questionType}
                                        onChange={(e) => setQuestionType(e.target.value)}
                                        className="w-full p-3 rounded-xl bg-gray-50 dark:bg-black/20 border border-gray-200 dark:border-white/10 focus:ring-2 focus:ring-purple-500 font-medium"
                                    >
                                        <option value="Multiple Choice">Multiple Choice</option>
                                        <option value="True/False">True / False</option>
                                        <option value="Mixed">Mixed</option>
                                    </select>
                                </div>

                                <div className="pt-6 border-t border-gray-100 dark:border-white/5">
                                    <button
                                        onClick={handleGenerate}
                                        disabled={!material.trim() && !file}
                                        className="w-full py-4 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-bold text-lg shadow-xl shadow-purple-500/20 hover:shadow-purple-500/40 transform transition-all hover:-translate-y-1 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                                    >
                                        <Bot className="w-5 h-5" />
                                        Generate Quiz
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            ) : (
                /* STEP 2: REVIEW AND EDIT */
                <div className="flex flex-col h-full overflow-hidden">
                    <div className="flex-none mb-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="relative">
                            <label className="absolute -top-2.5 left-3 bg-gray-50 dark:bg-[#050505] px-2 text-xs font-bold text-purple-600">Quiz Title</label>
                            <input
                                value={quizTitle}
                                onChange={(e) => setQuizTitle(e.target.value)}
                                className="w-full p-3 rounded-xl bg-white dark:bg-[#13141f] border border-gray-200 dark:border-white/10 focus:ring-2 focus:ring-purple-500 font-bold text-lg"
                            />
                        </div>
                        <div className="relative">
                            <label className="absolute -top-2.5 left-3 bg-gray-50 dark:bg-[#050505] px-2 text-xs font-bold text-gray-500">Description</label>
                            <input
                                value={quizDescription}
                                onChange={(e) => setQuizDescription(e.target.value)}
                                className="w-full p-3 rounded-xl bg-white dark:bg-[#13141f] border border-gray-200 dark:border-white/10 focus:ring-2 focus:ring-purple-500"
                            />
                        </div>
                    </div>

                    <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-6">
                        {generatedQuestions.map((q, idx) => (
                            <div key={idx} className="bg-white dark:bg-[#13141f] p-6 rounded-2xl border border-gray-200 dark:border-white/5 shadow-sm group">
                                <div className="flex items-start gap-4 mb-4">
                                    <span className="w-8 h-8 rounded-lg bg-gray-100 dark:bg-white/5 flex items-center justify-center text-sm font-bold text-gray-500">
                                        {idx + 1}
                                    </span>
                                    <div className="flex-1">
                                        <textarea
                                            value={q.question}
                                            onChange={(e) => handleQuestionChange(idx, 'question', e.target.value)}
                                            className="w-full p-2 rounded-lg bg-transparent border-none focus:bg-gray-50 dark:focus:bg-white/5 focus:ring-2 focus:ring-purple-500 font-medium text-lg resize-none"
                                            rows={2}
                                        />
                                    </div>
                                    <button
                                        onClick={() => {
                                            const newQs = [...generatedQuestions];
                                            newQs.splice(idx, 1);
                                            setGeneratedQuestions(newQs);
                                        }}
                                        className="text-gray-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                                    >
                                        Remove
                                    </button>
                                </div>

                                <div className="pl-12 grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
                                    {q.options?.map((opt, optIdx) => (
                                        <div
                                            key={optIdx}
                                            className={`relative p-3 rounded-xl border-2 transition-all flex items-center gap-3 ${q.correctAnswer === optIdx
                                                ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-500/10'
                                                : 'border-gray-100 dark:border-white/5 hover:border-gray-200 dark:hover:border-white/10'
                                                }`}
                                        >
                                            <button
                                                onClick={() => handleQuestionChange(idx, 'correctAnswer', optIdx)}
                                                className={`w-5 h-5 rounded-full border-2 flex items-center justify-center flex-shrink-0 ${q.correctAnswer === optIdx
                                                    ? 'border-emerald-500 bg-emerald-500 text-white'
                                                    : 'border-gray-300 dark:border-gray-600'
                                                    }`}
                                            >
                                                {q.correctAnswer === optIdx && <Check className="w-3 h-3" />}
                                            </button>
                                            <input
                                                value={opt}
                                                onChange={(e) => handleOptionChange(idx, optIdx, e.target.value)}
                                                className="flex-1 bg-transparent border-none focus:outline-none text-sm"
                                            />
                                        </div>
                                    ))}
                                </div>

                                <div className="pl-12">
                                    <label className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1 block">Explanation</label>
                                    <textarea
                                        value={q.explanation}
                                        onChange={(e) => handleQuestionChange(idx, 'explanation', e.target.value)}
                                        className="w-full p-3 rounded-xl bg-gray-50 dark:bg-black/20 border-none text-sm text-gray-600 dark:text-gray-400 resize-none"
                                        rows={2}
                                    />
                                </div>
                            </div>
                        ))}
                    </div>

                    <div className="flex-none pt-6 mt-6 border-t border-gray-200 dark:border-white/10 flex items-center justify-between">
                        <div className="flex items-center gap-4 text-sm text-gray-500">
                            <span>Total Questions: <strong className="text-gray-900 dark:text-white">{generatedQuestions.length}</strong></span>
                            <span>Estimated Time: <strong className="text-gray-900 dark:text-white">{Math.ceil(generatedQuestions.length * 1.5)} min</strong></span>
                        </div>
                        <div className="flex items-center gap-4">
                            <button
                                onClick={() => setStep(1)}
                                className="px-6 py-3 rounded-xl text-gray-600 dark:text-gray-400 font-bold hover:bg-gray-100 dark:hover:bg-white/5 transition-all"
                            >
                                Back to Edit
                            </button>
                            <button
                                onClick={handlePublish}
                                className="px-8 py-3 rounded-xl bg-green-500 text-white font-bold shadow-lg shadow-green-500/20 hover:shadow-green-500/40 hover:bg-green-600 transform transition-all hover:-translate-y-1 active:scale-95 flex items-center gap-2"
                            >
                                <Save className="w-5 h-5" />
                                Publish to Quiz Bank
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default AiQuizGenerator;
